version: '3'

services:

  # Зукипер для Kafka
  zookeeper:
    image: zookeeper:latest
    ports:
      - "2181:2181"

  # Kafka
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka:9090,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9090,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

  # Приложение для просмотра состояния Kafka
  kafdrop:
    image: obsidiandynamics/kafdrop
    depends_on:
      - kafka
    ports:
      - "9001:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9090

  # Redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: redis
      REDIS_USER: user
      REDIS_USER_PASSWORD: password

  # Приложение для просмотра состояния Redis
  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"

  # Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command: start-dev

  #PostGre
  core-v3-database:
    build: ./
    container_name: core-databases
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgadmin-data:/var/lib/pgAdmin
    depends_on:
      - zookeeper
      - kafka
      - redis
      - keycloak

volumes:
  zookeeper_data:
  kafka_data:
  redis_data:
  postgres_data:
  keycloak_data:
  common_config:
